# Generated by Django 4.1 on 2023-04-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='click_id',
        ),
    ]
